theme: jekyll-theme-minimal
layout: default
include:
  - "_img"
title: Булл-шитт бинго
description: от чего вам никогда не удастся
description: поменять хоть что-то к лучшему
description: в своей жизни
