theme: jekyll-theme-minimal
layout: default
include:
  - "_img"
title: Булл-шит бинго
description: игра для ит-возраста и безответственных корпоративов, в которую надо успеть сыграть пока будущее не превратилось в тыкву
author:
  name: Alexander Ivlev
  url: https://scr.ru/
