theme: jekyll-theme-minimal
layout: default
include:
  - "_img"
title: Булл-шит бинго
description: игра для ит-возраста и безответственных корпоративов
description: [О авторе](https://ivlev.github.io)
